version: '2'

services:
  app2:
    container_name: laravel_app2
    restart: unless-stopped
    tty: true
    build:
      context: ./
      dockerfile: Dockerfile 
    ports:
      - 8001:8000
    volumes:
      - ./:/var/www/html