version: '2'

services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.2-debian-10'
    container_name: laravel_mysql
    ports:
      - "3308:3306"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=laravel
      - MARIADB_DATABASE=laravel
      - MARIADB_PASSWORD=laravel
      
  app:
    container_name: laravel_app
    tty: true
    image: docker.io/bitnami/laravel:8-debian-10
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=laravel
      - DB_DATABASE=laravel
      - DB_PASSWORD=laravel
    depends_on:
      - mariadb
    ports:
      - 3000:3000
    volumes:
      - ./:/app